### ISSUE TITLE
Add the correct sense to all lateral axis definitions

### ISSUE THREAD

**Issue by moorepants** [mechmotum/baby-vibration#3]
In `data/sessions.yml` each session has the lateral axis of each IMU defined:

```yaml
  imu_lateral_axis:
    BotTrike: x
    FrontWheel: z
    RearWheel: -z
    SeatBot: x
    SeatHead: x
```

The IMUs are oriented on the vehicle such that one of the three body fixed sensor axes are approximately lined up with the horizontal lateral axis of the vehicle. These have to be added for each vehicle (probably could be stored in `data/vehicles.yml`). The correct sense of each axis needs to be recorded for the rotation and gravity subtraction to work correctly. If the positive sensor axis is pointing to the right of the vehicle (when facing forward) it should indicated as `x`, `y`, or `z`. If the positive sense of the sensor axis is pointing to the left of the vehicle, it should be `-x`, `-y`, or `-z`.
