### ISSUE TITLE
Add meta data about baby seat installed on the bike for each session

### ISSUE THREAD

**Issue by moorepants** [mechmotum/baby-vibration#9]
We need to add an entry to `sessions.yml` for `seat` and give it the various names of the seats we used. It is not true in all cases that the combination of bike + baby age = unique seat, as we tested the same baby age in two different seats on the same bike.

I think it makes sense to do this for the strollers too, because we have different seat configurations. Best to just log the seat explicitly for every session in case we need that info later.

For example:

```yaml
session018:
  date: 2024-12-16
  vehicle: trike
  baby_age: 3
  seat: pebble
  trial_bounds_file: events_Trike_5_3months.csv
  imu_lateral_axis:  # checked with: https://github.com/mechmotum/baby-vibration/issues/3#issuecomment-2550638125
    BotTrike: -y
    FrontWheel: -x
    RearWheel: -x
    SeatBot: x
    SeatHead: x
  imu_files:
    front_wheel: 2024-12-16_Trike_5_3months/2024-12-16_10.04.07_Trike_5_FW_SD_Session1/Trike_5_FW_Session1_S_FrontWheel_Calibrated_SD.csv
    rear_wheel: 2024-12-16_Trike_5_3months/2024-12-16_10.03.03_Trike_5_RW_SD_Session1/Trike_5_RW_Session1_S_RearWheel_Calibrated_SD.csv
    seat_bottom: 2024-12-16_Trike_5_3months/2024-12-16_10.02.40_Trike_5_SB_SD_Session1/Trike_5_SB_Session1_S_SeatBot_Calibrated_SD.csv
    seat_head: 2024-12-16_Trike_5_3months/2024-12-16_10.03.32_Trike_5_SH_SD_Session1/Trike_5_SH_Session1_S_SeatHead_Calibrated_SD.csv
    trike_bottom: 2024-12-16_Trike_5_3months/2024-12-16_10.02.23_Trike_5_BT_SD_Session1/Trike_5_BT_Session1_S_BotTrike_Calibrated_SD.csv
```

@GabrieleDello can you either add this to the file or provide the data?
